/**
 * Mock Data for Development
 * Sample tournaments, players, and standings
 */

import {
  Tournament,
  TournamentStanding,
  Platform,
  TournamentFormat,
  TournamentStatus,
  TimeControl,
  PlayerTitle,
} from "@/types";

export const mockTournaments: Tournament[] = [
  {
    id: "titled-tuesday-oct-29",
    name: "Titled Tuesday Late",
    platform: Platform.CHESS_COM,
    format: TournamentFormat.SWISS,
    status: TournamentStatus.COMPLETED,
    timeControl: TimeControl.BLITZ,
    startDate: "2024-10-29T18:00:00Z",
    endDate: "2024-10-29T21:30:00Z",
    prizePool: 1600,
    prizeCurrency: "USD",
    participantCount: 523,
    rounds: 11,
    featured: true,
    thumbnailUrl: "https://images.chesscomfiles.com/uploads/v1/images_users/tiny_mce/PedroPinhata/phpkXK09k.png",
    officialUrl: "https://www.chess.com/tournament/titled-tuesday",
    description: "Weekly blitz tournament for titled players with $1,600 prize pool",
  },
  {
    id: "world-rapid-2024",
    name: "World Rapid Championship 2024",
    platform: Platform.FIDE,
    format: TournamentFormat.SWISS,
    status: TournamentStatus.COMPLETED,
    timeControl: TimeControl.RAPID,
    startDate: "2024-10-27T10:00:00Z",
    endDate: "2024-10-29T18:00:00Z",
    prizePool: 175000,
    prizeCurrency: "USD",
    participantCount: 180,
    rounds: 13,
    featured: true,
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/FIDE_Logo.svg/200px-FIDE_Logo.svg.png",
    location: "New York, USA",
    officialUrl: "https://fide.com",
    description: "Official FIDE World Rapid Championship",
  },
  {
    id: "lichess-titled-arena-nov",
    name: "Lichess Titled Arena",
    platform: Platform.LICHESS,
    format: TournamentFormat.ARENA,
    status: TournamentStatus.UPCOMING,
    timeControl: TimeControl.BLITZ,
    startDate: "2024-11-05T19:00:00Z",
    endDate: "2024-11-05T20:30:00Z",
    prizePool: 250,
    prizeCurrency: "USD",
    participantCount: 350,
    featured: true,
    thumbnailUrl: "https://images.prismic.io/lichess/5cfd2630-2a8f-42fa-8838-b0c9d5cfb75c_lichess-box-1024.png",
    officialUrl: "https://lichess.org/tournament",
    description: "Monthly arena tournament for titled players",
  },
  {
    id: "speed-chess-championship-2024",
    name: "Speed Chess Championship 2024",
    platform: Platform.CHESS_COM,
    format: TournamentFormat.KNOCKOUT,
    status: TournamentStatus.ONGOING,
    timeControl: TimeControl.BLITZ,
    startDate: "2024-10-30T15:00:00Z",
    endDate: "2024-11-15T20:00:00Z",
    prizePool: 100000,
    prizeCurrency: "USD",
    participantCount: 32,
    thumbnailUrl: "https://images.chesscomfiles.com/uploads/v1/images_users/tiny_mce/PedroPinhata/phpkXK09k.png",
    officialUrl: "https://www.chess.com/tournament/speed-chess-championship",
    description: "Elite knockout tournament featuring the world's best speed chess players",
  },
  {
    id: "fide-grand-swiss-2024",
    name: "FIDE Grand Swiss 2024",
    platform: Platform.FIDE,
    format: TournamentFormat.SWISS,
    status: TournamentStatus.COMPLETED,
    timeControl: TimeControl.CLASSICAL,
    startDate: "2024-10-15T14:00:00Z",
    endDate: "2024-10-28T18:00:00Z",
    prizePool: 400000,
    prizeCurrency: "USD",
    participantCount: 156,
    rounds: 11,
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/FIDE_Logo.svg/200px-FIDE_Logo.svg.png",
    location: "Douglas, Isle of Man",
    officialUrl: "https://fide.com/grand-swiss",
    description: "Major qualifying event for the Candidates Tournament",
  },
  {
    id: "lichess-bullet-arena-oct-30",
    name: "Lichess Bullet Arena",
    platform: Platform.LICHESS,
    format: TournamentFormat.ARENA,
    status: TournamentStatus.UPCOMING,
    timeControl: TimeControl.BULLET,
    startDate: "2024-10-30T18:00:00Z",
    endDate: "2024-10-30T19:00:00Z",
    prizePool: 150,
    prizeCurrency: "USD",
    participantCount: 500,
    thumbnailUrl: "https://images.prismic.io/lichess/5cfd2630-2a8f-42fa-8838-b0c9d5cfb75c_lichess-box-1024.png",
    officialUrl: "https://lichess.org/tournament",
    description: "Fast-paced bullet tournament open to all players",
  },
  {
    id: "chesscom-blitz-titled-oct-31",
    name: "Chess.com Blitz Battle",
    platform: Platform.CHESS_COM,
    format: TournamentFormat.SWISS,
    status: TournamentStatus.UPCOMING,
    timeControl: TimeControl.BLITZ,
    startDate: "2024-10-31T20:00:00Z",
    endDate: "2024-10-31T23:00:00Z",
    prizePool: 2000,
    prizeCurrency: "USD",
    participantCount: 450,
    rounds: 9,
    thumbnailUrl: "https://images.chesscomfiles.com/uploads/v1/images_users/tiny_mce/PedroPinhata/phpkXK09k.png",
    officialUrl: "https://www.chess.com/tournament",
    description: "High-stakes blitz tournament with strong prize pool",
  },
  {
    id: "pro-chess-league-week-5",
    name: "PRO Chess League - Week 5",
    platform: Platform.CHESS_COM,
    format: TournamentFormat.ROUND_ROBIN,
    status: TournamentStatus.ONGOING,
    timeControl: TimeControl.RAPID,
    startDate: "2024-10-29T19:00:00Z",
    endDate: "2024-10-29T22:00:00Z",
    prizePool: 50000,
    prizeCurrency: "USD",
    participantCount: 48,
    thumbnailUrl: "https://images.chesscomfiles.com/uploads/v1/images_users/tiny_mce/PedroPinhata/phpkXK09k.png",
    officialUrl: "https://www.chess.com/article/pro-chess-league",
    description: "Team-based professional chess league",
  },
];

export const mockStandings: TournamentStanding[] = [
  {
    rank: 1,
    playerId: "hikaru",
    playerName: "Hikaru Nakamura",
    playerTitle: PlayerTitle.GM,
    playerCountry: "US",
    score: 10,
    rating: 3265,
    performanceRating: 3012,
    buchholzScore: 84.5,
    wins: 10,
    draws: 0,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 6,
    blackGames: 5,
  },
  {
    rank: 2,
    playerId: "magnus",
    playerName: "Magnus Carlsen",
    playerTitle: PlayerTitle.GM,
    playerCountry: "NO",
    score: 9.5,
    rating: 3210,
    performanceRating: 2980,
    buchholzScore: 83.0,
    wins: 9,
    draws: 1,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 5,
    blackGames: 6,
  },
  {
    rank: 3,
    playerId: "alireza",
    playerName: "Alireza Firouzja",
    playerTitle: PlayerTitle.GM,
    playerCountry: "FR",
    score: 9.5,
    rating: 3195,
    performanceRating: 2975,
    buchholzScore: 82.5,
    wins: 9,
    draws: 1,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 6,
    blackGames: 5,
  },
  {
    rank: 4,
    playerId: "fabiano",
    playerName: "Fabiano Caruana",
    playerTitle: PlayerTitle.GM,
    playerCountry: "US",
    score: 9,
    rating: 3150,
    performanceRating: 2950,
    buchholzScore: 81.5,
    wins: 8,
    draws: 2,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 5,
    blackGames: 6,
  },
  {
    rank: 5,
    playerId: "wesley",
    playerName: "Wesley So",
    playerTitle: PlayerTitle.GM,
    playerCountry: "US",
    score: 9,
    rating: 3140,
    performanceRating: 2945,
    buchholzScore: 80.0,
    wins: 8,
    draws: 2,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 6,
    blackGames: 5,
  },
  {
    rank: 6,
    playerId: "levon",
    playerName: "Levon Aronian",
    playerTitle: PlayerTitle.GM,
    playerCountry: "US",
    score: 8.5,
    rating: 3120,
    performanceRating: 2920,
    buchholzScore: 79.5,
    wins: 7,
    draws: 3,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 5,
    blackGames: 6,
  },
  {
    rank: 7,
    playerId: "anish",
    playerName: "Anish Giri",
    playerTitle: PlayerTitle.GM,
    playerCountry: "NL",
    score: 8.5,
    rating: 3110,
    performanceRating: 2915,
    buchholzScore: 78.5,
    wins: 7,
    draws: 3,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 6,
    blackGames: 5,
  },
  {
    rank: 8,
    playerId: "ian",
    playerName: "Ian Nepomniachtchi",
    playerTitle: PlayerTitle.GM,
    playerCountry: "RU",
    score: 8,
    rating: 3105,
    performanceRating: 2900,
    buchholzScore: 77.0,
    wins: 7,
    draws: 2,
    losses: 2,
    gamesPlayed: 11,
    whiteGames: 5,
    blackGames: 6,
  },
  {
    rank: 9,
    playerId: "ding",
    playerName: "Ding Liren",
    playerTitle: PlayerTitle.GM,
    playerCountry: "CN",
    score: 8,
    rating: 3095,
    performanceRating: 2895,
    buchholzScore: 76.5,
    wins: 6,
    draws: 4,
    losses: 1,
    gamesPlayed: 11,
    whiteGames: 6,
    blackGames: 5,
  },
  {
    rank: 10,
    playerId: "maxime",
    playerName: "Maxime Vachier-Lagrave",
    playerTitle: PlayerTitle.GM,
    playerCountry: "FR",
    score: 8,
    rating: 3080,
    performanceRating: 2890,
    buchholzScore: 75.0,
    wins: 7,
    draws: 2,
    losses: 2,
    gamesPlayed: 11,
    whiteGames: 5,
    blackGames: 6,
  },
];

// Mock Forum Posts
export const mockForumPosts = [
  {
    id: "post-1",
    title: "Titled Tuesday Discussion - October 29th Results",
    author: "ChessFan123",
    replies: 47,
    views: 1203,
    lastActivity: "2 hours ago",
    category: "Tournaments",
  },
  {
    id: "post-2",
    title: "Best opening preparation for rapid tournaments?",
    author: "TacticsMaster",
    replies: 89,
    views: 2456,
    lastActivity: "5 hours ago",
    category: "Strategy",
  },
  {
    id: "post-3",
    title: "Magnus Carlsen's performance in recent online events",
    author: "ChessAnalyst",
    replies: 134,
    views: 3872,
    lastActivity: "1 day ago",
    category: "Players",
  },
  {
    id: "post-4",
    title: "How to improve from 2000 to 2200 rating?",
    author: "AspiringIM",
    replies: 67,
    views: 1891,
    lastActivity: "3 hours ago",
    category: "Improvement",
  },
  {
    id: "post-5",
    title: "FIDE Grand Swiss 2024 - Post-Tournament Analysis",
    author: "GrandmasterPro",
    replies: 92,
    views: 2634,
    lastActivity: "6 hours ago",
    category: "Tournaments",
  },
];

// Mock Player Rankings - FIDE Classical
export const mockFideClassicalRankings = [
  {
    rank: 1,
    playerId: "hikaru",
    playerName: "Hikaru Nakamura",
    title: "GM",
    rating: 3265,
    country: "US",
    ratingChange: 12,
  },
  {
    rank: 2,
    playerId: "magnus",
    playerName: "Magnus Carlsen",
    title: "GM",
    rating: 3210,
    country: "NO",
    ratingChange: -5,
  },
  {
    rank: 3,
    playerId: "alireza",
    playerName: "Alireza Firouzja",
    title: "GM",
    rating: 3195,
    country: "FR",
    ratingChange: 8,
  },
  {
    rank: 4,
    playerId: "fabiano",
    playerName: "Fabiano Caruana",
    title: "GM",
    rating: 3150,
    country: "US",
    ratingChange: 3,
  },
  {
    rank: 5,
    playerId: "wesley",
    playerName: "Wesley So",
    title: "GM",
    rating: 3140,
    country: "US",
    ratingChange: -2,
  },
  {
    rank: 6,
    playerId: "levon",
    playerName: "Levon Aronian",
    title: "GM",
    rating: 3120,
    country: "US",
    ratingChange: 0,
  },
  {
    rank: 7,
    playerId: "anish",
    playerName: "Anish Giri",
    title: "GM",
    rating: 3110,
    country: "NL",
    ratingChange: 5,
  },
  {
    rank: 8,
    playerId: "ian",
    playerName: "Ian Nepomniachtchi",
    title: "GM",
    rating: 3105,
    country: "RU",
    ratingChange: -7,
  },
  {
    rank: 9,
    playerId: "ding",
    playerName: "Ding Liren",
    title: "GM",
    rating: 3095,
    country: "CN",
    ratingChange: 4,
  },
  {
    rank: 10,
    playerId: "maxime",
    playerName: "Maxime Vachier-Lagrave",
    title: "GM",
    rating: 3080,
    country: "FR",
    ratingChange: 1,
  },
];

// Mock Player Rankings - FIDE Rapid
export const mockFideRapidRankings = [
  { rank: 1, playerId: "magnus", playerName: "Magnus Carlsen", title: "GM", rating: 2856, country: "NO", ratingChange: 8 },
  { rank: 2, playerId: "hikaru", playerName: "Hikaru Nakamura", title: "GM", rating: 2847, country: "US", ratingChange: 5 },
  { rank: 3, playerId: "fabiano", playerName: "Fabiano Caruana", title: "GM", rating: 2822, country: "US", ratingChange: -3 },
  { rank: 4, playerId: "alireza", playerName: "Alireza Firouzja", title: "GM", rating: 2815, country: "FR", ratingChange: 12 },
  { rank: 5, playerId: "anish", playerName: "Anish Giri", title: "GM", rating: 2803, country: "NL", ratingChange: 0 },
  { rank: 6, playerId: "wesley", playerName: "Wesley So", title: "GM", rating: 2795, country: "US", ratingChange: 7 },
  { rank: 7, playerId: "levon", playerName: "Levon Aronian", title: "GM", rating: 2789, country: "US", ratingChange: -2 },
  { rank: 8, playerId: "ding", playerName: "Ding Liren", title: "GM", rating: 2780, country: "CN", ratingChange: 4 },
  { rank: 9, playerId: "ian", playerName: "Ian Nepomniachtchi", title: "GM", rating: 2775, country: "RU", ratingChange: -5 },
  { rank: 10, playerId: "maxime", playerName: "Maxime Vachier-Lagrave", title: "GM", rating: 2768, country: "FR", ratingChange: 2 },
];

// Mock Player Rankings - FIDE Blitz
export const mockFideBlitzRankings = [
  { rank: 1, playerId: "magnus", playerName: "Magnus Carlsen", title: "GM", rating: 2942, country: "NO", ratingChange: 15 },
  { rank: 2, playerId: "hikaru", playerName: "Hikaru Nakamura", title: "GM", rating: 2925, country: "US", ratingChange: 18 },
  { rank: 3, playerId: "alireza", playerName: "Alireza Firouzja", title: "GM", rating: 2898, country: "FR", ratingChange: 10 },
  { rank: 4, playerId: "ian", playerName: "Ian Nepomniachtchi", title: "GM", rating: 2876, country: "RU", ratingChange: 6 },
  { rank: 5, playerId: "fabiano", playerName: "Fabiano Caruana", title: "GM", rating: 2865, country: "US", ratingChange: -4 },
  { rank: 6, playerId: "wesley", playerName: "Wesley So", title: "GM", rating: 2850, country: "US", ratingChange: 3 },
  { rank: 7, playerId: "maxime", playerName: "Maxime Vachier-Lagrave", title: "GM", rating: 2845, country: "FR", ratingChange: 8 },
  { rank: 8, playerId: "levon", playerName: "Levon Aronian", title: "GM", rating: 2838, country: "US", ratingChange: -2 },
  { rank: 9, playerId: "ding", playerName: "Ding Liren", title: "GM", rating: 2830, country: "CN", ratingChange: 1 },
  { rank: 10, playerId: "anish", playerName: "Anish Giri", title: "GM", rating: 2825, country: "NL", ratingChange: 5 },
];

// Mock Player Rankings - Chess.com
export const mockChessComRankings = [
  { rank: 1, playerId: "hikaru", playerName: "Hikaru Nakamura", title: "GM", rating: 3265, country: "US", ratingChange: 12 },
  { rank: 2, playerId: "magnus", playerName: "Magnus Carlsen", title: "GM", rating: 3210, country: "NO", ratingChange: -5 },
  { rank: 3, playerId: "alireza", playerName: "Alireza Firouzja", title: "GM", rating: 3195, country: "FR", ratingChange: 8 },
  { rank: 4, playerId: "fabiano", playerName: "Fabiano Caruana", title: "GM", rating: 3150, country: "US", ratingChange: 3 },
  { rank: 5, playerId: "danya", playerName: "Daniel Naroditsky", title: "GM", rating: 3142, country: "US", ratingChange: 15 },
  { rank: 6, playerId: "wesley", playerName: "Wesley So", title: "GM", rating: 3140, country: "US", ratingChange: -2 },
  { rank: 7, playerId: "levon", playerName: "Levon Aronian", title: "GM", rating: 3120, country: "US", ratingChange: 0 },
  { rank: 8, playerId: "anish", playerName: "Anish Giri", title: "GM", rating: 3110, country: "NL", ratingChange: 5 },
  { rank: 9, playerId: "ian", playerName: "Ian Nepomniachtchi", title: "GM", rating: 3105, country: "RU", ratingChange: -7 },
  { rank: 10, playerId: "ding", playerName: "Ding Liren", title: "GM", rating: 3095, country: "CN", ratingChange: 4 },
];

// Mock Player Rankings - Lichess
export const mockLichessRankings = [
  { rank: 1, playerId: "magnus", playerName: "Magnus Carlsen", title: "GM", rating: 3201, country: "NO", ratingChange: 10 },
  { rank: 2, playerId: "alireza", playerName: "Alireza Firouzja", title: "GM", rating: 3185, country: "FR", ratingChange: 22 },
  { rank: 3, playerId: "hikaru", playerName: "Hikaru Nakamura", title: "GM", rating: 3175, country: "US", ratingChange: 5 },
  { rank: 4, playerId: "danya", playerName: "Daniel Naroditsky", title: "GM", rating: 3158, country: "US", ratingChange: 18 },
  { rank: 5, playerId: "fabiano", playerName: "Fabiano Caruana", title: "GM", rating: 3140, country: "US", ratingChange: 3 },
  { rank: 6, playerId: "wesley", playerName: "Wesley So", title: "GM", rating: 3125, country: "US", ratingChange: -5 },
  { rank: 7, playerId: "ian", playerName: "Ian Nepomniachtchi", title: "GM", rating: 3110, country: "RU", ratingChange: 8 },
  { rank: 8, playerId: "anish", playerName: "Anish Giri", title: "GM", rating: 3095, country: "NL", ratingChange: 2 },
  { rank: 9, playerId: "maxime", playerName: "Maxime Vachier-Lagrave", title: "GM", rating: 3088, country: "FR", ratingChange: 12 },
  { rank: 10, playerId: "levon", playerName: "Levon Aronian", title: "GM", rating: 3075, country: "US", ratingChange: -3 },
];

// Legacy export for backwards compatibility
export const mockPlayerRankings = mockFideClassicalRankings;

// Mock Top Performers
export const mockTopPerformers = [
  {
    playerId: "alireza",
    playerName: "Alireza Firouzja",
    title: "GM",
    achievement: "Won 3 consecutive tournaments",
    stat: "+127 rating points",
    trend: "hot" as const,
  },
  {
    playerId: "danya",
    playerName: "Daniel Naroditsky",
    title: "GM",
    achievement: "15-game winning streak",
    stat: "100% win rate",
    trend: "hot" as const,
  },
  {
    playerId: "hikaru",
    playerName: "Hikaru Nakamura",
    title: "GM",
    achievement: "Speed Chess Championship winner",
    stat: "+85 rating points",
    trend: "up" as const,
  },
  {
    playerId: "praggnanandhaa",
    playerName: "Praggnanandhaa R",
    title: "GM",
    achievement: "Youngest to reach 2750 rapid",
    stat: "Rising star",
    trend: "new" as const,
  },
  {
    playerId: "magnus",
    playerName: "Magnus Carlsen",
    title: "GM",
    achievement: "Defending world rapid champion",
    stat: "12 wins in a row",
    trend: "up" as const,
  },
];

export function getTournamentById(id: string): Tournament | undefined {
  return mockTournaments.find((t) => t.id === id);
}

export function getStandingsForTournament(tournamentId: string): TournamentStanding[] {
  // In a real app, this would fetch from API based on tournament ID
  return mockStandings;
}
